// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vcore.h for the primary calling header

#ifndef VERILATED_VCORE___024ROOT_H_
#define VERILATED_VCORE___024ROOT_H_  // guard

#include "verilated.h"


class Vcore__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vcore___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(clk_m,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(rst_m,0,0);
        CData/*0:0*/ core__DOT__jump1;
        CData/*0:0*/ core__DOT__jump2;
        CData/*1:0*/ core__DOT__consumed;
        CData/*0:0*/ core__DOT__rename_busy;
        CData/*0:0*/ core__DOT__flush;
        CData/*0:0*/ core__DOT__ROB_busy;
        CData/*0:0*/ core__DOT__dispatch_busy;
        CData/*6:0*/ core__DOT__flush_sqN;
        CData/*0:0*/ core__DOT__fetch__DOT__q;
        CData/*0:0*/ core__DOT__fetch__DOT__invalidate;
        CData/*0:0*/ core__DOT__fetch__DOT__IA__DOT__pc_align;
        CData/*0:0*/ core__DOT__fetch__DOT__JTA1__DOT__jump_valid;
        CData/*0:0*/ core__DOT__fetch__DOT__JTA1__DOT__jump_index;
        CData/*3:0*/ core__DOT__fetch__DOT__FB__DOT__head;
        CData/*3:0*/ core__DOT__fetch__DOT__FB__DOT__tail;
        CData/*4:0*/ core__DOT__fetch__DOT__FB__DOT__count;
        CData/*6:0*/ core__DOT__fetch__DOT__FB__DOT__sqN_counter;
        CData/*1:0*/ core__DOT__fetch__DOT__FB__DOT__in_valid_count;
        CData/*1:0*/ core__DOT__fetch__DOT__FB__DOT__out_count;
        CData/*0:0*/ core__DOT__fetch__DOT__FB__DOT__can_read;
        CData/*3:0*/ core__DOT__fetch__DOT__FB__DOT__idx_head;
        CData/*2:0*/ core__DOT__decode__DOT__Decoder__DOT__IG__DOT__funct3;
        CData/*6:0*/ core__DOT__decode__DOT__Decoder__DOT__IG__DOT__opcode;
        CData/*1:0*/ core__DOT__rename__DOT__req_valid;
        CData/*0:0*/ core__DOT__rename__DOT__chkpt_need;
        CData/*5:0*/ core__DOT__rename__DOT____Vlvbound_h1e224336__0;
        CData/*0:0*/ core__DOT__dispatch__DOT__DU__DOT__packet_done;
        CData/*6:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_h1aff00cd__0;
        CData/*3:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_h0a971624__0;
        CData/*5:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_h0c642120__0;
        CData/*5:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_h0c63fe7a__0;
        CData/*5:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_h0c65601b__0;
        CData/*6:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_he58089a1__0;
        CData/*3:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_h8cde0a2a__0;
        CData/*5:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_hdbd66b77__0;
        CData/*5:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_hdbd65884__0;
        CData/*5:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_hdbd638f6__0;
        CData/*0:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_heace712a__0;
        CData/*4:0*/ core__DOT__dispatch__DOT__BC__DOT__count;
        CData/*1:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__OUT_jump_type;
        CData/*1:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__OUT_jump_type;
        CData/*0:0*/ core__DOT__issue__DOT__ta_gen2__DOT__oldest_idx;
        CData/*6:0*/ core__DOT__issue__DOT__ta_gen2__DOT__oldest_sqN;
        CData/*3:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__tail;
        CData/*7:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__ready_mask;
        CData/*2:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__issue_idx;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__issue_found;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__sel1;
        CData/*1:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__sel2;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__is_jump;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__issue_valid;
        CData/*3:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT____Vcellinp__bc__br_type;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r1;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r2;
        CData/*3:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__next_tail;
        CData/*6:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__unnamedblk9__DOT__diff;
        CData/*3:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__tail;
        CData/*7:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__ready_mask;
        CData/*2:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__issue_idx;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__issue_found;
    };
    struct {
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__sel1;
        CData/*1:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__sel2;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__is_jump;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__issue_valid;
        CData/*3:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT____Vcellinp__bc__br_type;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r1;
        CData/*0:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r2;
        CData/*3:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__next_tail;
        CData/*6:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__unnamedblk9__DOT__diff;
        CData/*3:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__tail;
        CData/*7:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__ready_mask;
        CData/*2:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__issue_idx;
        CData/*0:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__issue_found;
        CData/*0:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__issue_valid;
        CData/*0:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r1;
        CData/*0:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r2;
        CData/*3:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__v_tail;
        CData/*6:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__unnamedblk9__DOT__diff;
        CData/*3:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__tail;
        CData/*7:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__ready_mask;
        CData/*2:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__issue_idx;
        CData/*0:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__issue_found;
        CData/*0:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__issue_valid;
        CData/*0:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r1;
        CData/*0:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__r2;
        CData/*3:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__v_tail;
        CData/*6:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__unnamedblk9__DOT__diff;
        CData/*0:0*/ core__DOT__flush_controller__DOT__unnamedblk1__DOT__valid0;
        CData/*0:0*/ core__DOT__flush_controller__DOT__unnamedblk1__DOT__valid1;
        CData/*6:0*/ core__DOT__flush_controller__DOT__unnamedblk1__DOT__diff;
        CData/*2:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__state;
        CData/*2:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_valid;
        CData/*5:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_count;
        CData/*0:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_quot_sign;
        CData/*0:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_rem_sign;
        CData/*0:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_by_zero;
        CData/*0:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk3__DOT__s1;
        CData/*0:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk3__DOT__s2;
        CData/*0:0*/ core__DOT__execute__DOT__gen_agu_fu__BRA__0__KET____DOT__AGU_i__DOT__is_load;
        CData/*0:0*/ core__DOT__execute__DOT__gen_agu_fu__BRA__0__KET____DOT__AGU_i__DOT__is_store;
        CData/*1:0*/ core__DOT__execute__DOT__gen_agu_fu__BRA__0__KET____DOT__AGU_i__DOT__data_size;
        CData/*0:0*/ core__DOT__execute__DOT__gen_agu_fu__BRA__0__KET____DOT__AGU_i__DOT__is_unsigned;
        CData/*0:0*/ core__DOT__lsu__DOT__is_store;
        CData/*0:0*/ core__DOT__lsu__DOT__is_load;
        CData/*7:0*/ core__DOT__lsu__DOT__stb_alloc;
        CData/*0:0*/ core__DOT__lsu__DOT__str_busy;
        CData/*3:0*/ core__DOT__lsu__DOT__u_stb__DOT__tail_ptr;
        CData/*3:0*/ core__DOT__lsu__DOT__u_stb__DOT__drain_ptr;
        CData/*4:0*/ core__DOT__lsu__DOT__u_stb__DOT__count;
        CData/*3:0*/ core__DOT__lsu__DOT__u_stb__DOT__new_tail;
        CData/*3:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk4__DOT__idx;
        CData/*4:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk7__DOT__drain_inc;
        CData/*3:0*/ core__DOT__lsu__DOT__u_ldb__DOT__alloc_idx;
        CData/*3:0*/ core__DOT__lsu__DOT__u_ldb__DOT__ta_wb_idx;
        CData/*3:0*/ core__DOT__lsu__DOT__u_ldb__DOT__broadcast_idx;
        CData/*3:0*/ core__DOT__lsu__DOT__u_ldb__DOT__count;
        CData/*3:0*/ core__DOT__lsu__DOT__u_ldb__DOT__stall;
        CData/*3:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk5__DOT__unnamedblk6__DOT__be;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk5__DOT__unnamedblk6__DOT__bsel;
        CData/*6:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk5__DOT__unnamedblk6__DOT__boff;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__0__KET____DOT__u_wr_sync__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__0__KET____DOT__u_wr_sync__DOT__ff2;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__0__KET____DOT__u_rd_sync__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__0__KET____DOT__u_rd_sync__DOT__ff2;
    };
    struct {
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__1__KET____DOT__u_wr_sync__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__1__KET____DOT__u_wr_sync__DOT__ff2;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__1__KET____DOT__u_rd_sync__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_req_sync__BRA__1__KET____DOT__u_rd_sync__DOT__ff2;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__0__KET____DOT__u_wr_ack__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__0__KET____DOT__u_wr_ack__DOT__ff2;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__0__KET____DOT__u_rd_ack__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__0__KET____DOT__u_rd_ack__DOT__ff2;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__1__KET____DOT__u_wr_ack__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__1__KET____DOT__u_wr_ack__DOT__ff2;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__1__KET____DOT__u_rd_ack__DOT__ff1;
        CData/*0:0*/ core__DOT__lsu__DOT__u_dmem__DOT__g_ack_sync__BRA__1__KET____DOT__u_rd_ack__DOT__ff2;
        CData/*1:0*/ core__DOT__ROB__DOT__commit;
        CData/*1:0*/ core__DOT__ROB__DOT__dataout_valid;
        CData/*1:0*/ core__DOT__ROB__DOT__write_en;
        CData/*6:0*/ core__DOT__ROB__DOT__count;
        CData/*6:0*/ core__DOT__ROB__DOT__next_count;
        CData/*5:0*/ core__DOT__ROB__DOT__head;
        CData/*5:0*/ core__DOT__ROB__DOT__tail;
        CData/*5:0*/ core__DOT__ROB__DOT__next_head;
        CData/*5:0*/ core__DOT__ROB__DOT__next_tail;
        CData/*1:0*/ core__DOT__ROB__DOT__num_wr;
        CData/*1:0*/ core__DOT__ROB__DOT__num_commit;
        CData/*0:0*/ core__DOT__ROB__DOT__empty;
        CData/*4:0*/ __Vdly__core__DOT__fetch__DOT__FB__DOT__count;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v0;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v64;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v64;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v65;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v66;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v67;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v68;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v69;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v70;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v71;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v72;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v73;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v74;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v75;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v76;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v77;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v78;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v79;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v80;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v81;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v82;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v83;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v84;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v85;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v86;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v87;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v88;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v89;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v90;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v91;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v92;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v93;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v94;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v95;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v96;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v97;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v98;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v99;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v100;
    };
    struct {
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v101;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v102;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v103;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v104;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v105;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v106;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v107;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v108;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v109;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v110;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v111;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v112;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v113;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v114;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v115;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v116;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v117;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v118;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v119;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v120;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v121;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v122;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v123;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v124;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v125;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v126;
        CData/*0:0*/ __Vdlyvval__core__DOT__rename__DOT__tag_buffer__v127;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v128;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v128;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v129;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v129;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v130;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v130;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v131;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v131;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v132;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v132;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v133;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v134;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v135;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v135;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v136;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v137;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v138;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v138;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v139;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v140;
        CData/*0:0*/ __Vdlyvset__core__DOT__rename__DOT__tag_buffer__v140;
        CData/*5:0*/ __Vdlyvdim0__core__DOT__rename__DOT__tag_buffer__v141;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v64;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v64;
        CData/*0:0*/ __Vdlyvset__core__DOT__dispatch__DOT__BC__DOT__free__v64;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v65;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v65;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v66;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v66;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v67;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v67;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v68;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v68;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v69;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v69;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v70;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v70;
    };
    struct {
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v71;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v71;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v72;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v72;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v73;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v73;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v74;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v74;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v75;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v75;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v76;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v76;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v77;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v77;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v78;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v78;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v79;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v79;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v80;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v80;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v81;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v81;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v82;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v82;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v83;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v83;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v84;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v84;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v85;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v85;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v86;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v86;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v87;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v87;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v88;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v88;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v89;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v89;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v90;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v90;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v91;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v91;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v92;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v92;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v93;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v93;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v94;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v94;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v95;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v95;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v96;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v96;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v97;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v97;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v98;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v98;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v99;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v99;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v100;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v100;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v101;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v101;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v102;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v102;
    };
    struct {
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v103;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v103;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v104;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v104;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v105;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v105;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v106;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v106;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v107;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v107;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v108;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v108;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v109;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v109;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v110;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v110;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v111;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v111;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v112;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v112;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v113;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v113;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v114;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v114;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v115;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v115;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v116;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v116;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v117;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v117;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v118;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v118;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v119;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v119;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v120;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v120;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v121;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v121;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v122;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v122;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v123;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v123;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v124;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v124;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v125;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v125;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v126;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v126;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__dispatch__DOT__BC__DOT__free__v127;
        CData/*0:0*/ __Vdlyvval__core__DOT__dispatch__DOT__BC__DOT__free__v127;
        CData/*0:0*/ __Vdlyvset__core__DOT__int_cdb_lines__v0;
        CData/*0:0*/ __Vdlyvset__core__DOT__int_cdb_lines__v3;
        CData/*0:0*/ __Vdlyvset__core__DOT__int_cdb_lines__v4;
        CData/*0:0*/ __Vdlyvset__core__DOT__int_cdb_lines__v5;
        CData/*0:0*/ __Vdlyvset__core__DOT__int_cdb_lines__v6;
        CData/*2:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_valid;
        CData/*6:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_sqN__v0;
        CData/*6:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_sqN__v1;
        CData/*6:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_sqN__v2;
        CData/*5:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_tag__v0;
        CData/*5:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_tag__v1;
        CData/*5:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_tag__v2;
        CData/*3:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_oper__v0;
        CData/*3:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_oper__v1;
    };
    struct {
        CData/*3:0*/ __Vdlyvval__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_oper__v2;
        CData/*2:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__state;
        CData/*5:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_count;
        CData/*0:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_quot_sign;
        CData/*0:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_rem_sign;
        CData/*0:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_by_zero;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v0;
        CData/*3:0*/ __Vdly__core__DOT__lsu__DOT__u_ldb__DOT__count;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v1;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v16;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v17;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v18;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v19;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v20;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v21;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v22;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v23;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v24;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v25;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v26;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v27;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v28;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v29;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v30;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v31;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v32;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v32;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v33;
        CData/*6:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v33;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v34;
        CData/*5:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v34;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v35;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v36;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v37;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v37;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v38;
        CData/*0:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v38;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v39;
        CData/*1:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v39;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v40;
        CData/*0:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v40;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v41;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v43;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v45;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v47;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v49;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v51;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v53;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v55;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v57;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v59;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v61;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v63;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v65;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v67;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v69;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v71;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v73;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v75;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v77;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v79;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v81;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v83;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v85;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v87;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v89;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v91;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v93;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v95;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v97;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v99;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v101;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v103;
        CData/*3:0*/ __Vdlyvdim0__core__DOT__lsu__DOT__u_ldb__DOT__entries__v105;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_ldb__DOT__entries__v105;
        CData/*0:0*/ __Vdlyvset__core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__queue__v0;
        CData/*3:0*/ __Vdly__core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__tail;
        CData/*0:0*/ __Vdlyvset__core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__queue__v1;
        CData/*0:0*/ __Vdlyvset__core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__queue__v8;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__ldb_mem_resp__v0;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__ldb_mem_resp__v2;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__ldb_mem_resp__v3;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__ldb_mem_resp__v5;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__ldb_mem_resp__v6;
        CData/*0:0*/ __Vdlyvset__core__DOT__commit_packet__v0;
        CData/*0:0*/ __Vdlyvset__core__DOT__commit_packet__v2;
        CData/*0:0*/ __Vdlyvset__core__DOT__commit_packet__v3;
        CData/*6:0*/ __Vdlyvval__core__DOT__commit_packet__v4;
        CData/*0:0*/ __Vdlyvset__core__DOT__commit_packet__v4;
        CData/*5:0*/ __Vdlyvval__core__DOT__commit_packet__v5;
        CData/*4:0*/ __Vdlyvval__core__DOT__commit_packet__v6;
        CData/*0:0*/ __Vdlyvset__core__DOT__commit_packet__v8;
        CData/*6:0*/ __Vdlyvval__core__DOT__commit_packet__v9;
        CData/*0:0*/ __Vdlyvset__core__DOT__commit_packet__v9;
        CData/*5:0*/ __Vdlyvval__core__DOT__commit_packet__v10;
        CData/*4:0*/ __Vdlyvval__core__DOT__commit_packet__v11;
        CData/*0:0*/ __Vdlyvset__core__DOT__commit_packet__v13;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__wr_ack_mem__v0;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__wr_ack_mem__v2;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__wr_ack_mem__v4;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__wr_ack_mem__v5;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__rd_ack_mem__v0;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__rd_ack_mem__v2;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__rd_data_mem__v0;
        CData/*0:0*/ __Vdlyvset__core__DOT__lsu__DOT__u_dmem__DOT__rd_data_mem__v1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__core__DOT__flush__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__core__DOT__flush__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_m__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_m__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ core__DOT__decode__DOT__Decoder__DOT__IG__DOT__imm12;
        SData/*12:0*/ core__DOT__decode__DOT__Decoder__DOT__IG__DOT__imm13;
        SData/*13:0*/ core__DOT__lsu__DOT__ldb_alloc;
        SData/*15:0*/ core__DOT__lsu__DOT__u_stb__DOT__on_flush_valid;
        IData/*31:0*/ core__DOT__jta1;
        IData/*31:0*/ core__DOT__jta2;
        IData/*31:0*/ core__DOT__prefetch__DOT__in_pc;
        IData/*31:0*/ core__DOT__prefetch__DOT__PC__DOT__pc_reg;
        IData/*31:0*/ core__DOT__prefetch__DOT__IMEM__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ core__DOT__prefetch__DOT__IMEM__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ core__DOT__fetch__DOT__iw;
        IData/*31:0*/ core__DOT__fetch__DOT__FB__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ core__DOT__decode__DOT__unnamedblk1__DOT__i;
    };
    struct {
        IData/*20:0*/ core__DOT__decode__DOT__Decoder__DOT__IG__DOT__imm21;
        IData/*31:0*/ core__DOT__decode__DOT__Decoder__DOT__IG__DOT__iw;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk9__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk11__DOT__unnamedblk12__DOT__r;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk11__DOT__unnamedblk13__DOT__b;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk14__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk14__DOT__unnamedblk15__DOT__r;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk14__DOT__unnamedblk16__DOT__b;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk17__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk18__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk19__DOT__b;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk20__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk21__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk22__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk23__DOT__r;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk24__DOT__r;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk25__DOT__i;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk26__DOT__r;
        IData/*31:0*/ core__DOT__rename__DOT__unnamedblk27__DOT__i;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk1__DOT__g_alu_assign__DOT__unnamedblk2__DOT__s;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk3__DOT__unnamedblk4__DOT__s;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk5__DOT__unnamedblk6__DOT__s;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk12__DOT__p;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk13__DOT__p;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk14__DOT__p;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk15__DOT__i;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk16__DOT__i;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT__unnamedblk17__DOT__i;
        IData/*31:0*/ core__DOT__dispatch__DOT__DU__DOT____Vlvbound_h09f7461c__0;
        IData/*31:0*/ core__DOT__dispatch__DOT__BC__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ core__DOT__dispatch__DOT__BC__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ core__DOT__dispatch__DOT__BC__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ core__DOT__dispatch__DOT__BC__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__imm;
        IData/*31:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__rs1_result;
        IData/*31:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__OUT_pc;
        IData/*31:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__imm;
        IData/*31:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__rs1_result;
        IData/*31:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__OUT_pc;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__rs1_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__rs2_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__unnamedblk12__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk13__DOT__i;
        VlWide<4>/*104:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT____VdfgTmp_h256fc990__0;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__pe__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__rs1_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__rs2_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__unnamedblk12__DOT__j;
    };
    struct {
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk13__DOT__i;
        VlWide<4>/*104:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT____VdfgTmp_h256fc990__0;
        IData/*31:0*/ core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__pe__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__rs1_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__rs2_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__unnamedblk12__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk13__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT____VdfgTmp_h256a4fc8__0;
        IData/*31:0*/ core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__pe__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__rs1_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__rs2_data_selected;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk11__DOT__unnamedblk12__DOT__j;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__unnamedblk13__DOT__i;
        VlWide<3>/*64:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT____VdfgTmp_h25684f9f__0;
        IData/*31:0*/ core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__pe__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ core__DOT__execute__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ core__DOT__execute__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ core__DOT__execute__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ core__DOT__execute__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ core__DOT__execute__DOT__gen_alu_fu__BRA__0__KET____DOT__ALU_i__DOT__alu_result;
        IData/*31:0*/ core__DOT__execute__DOT__gen_alu_fu__BRA__1__KET____DOT__ALU_i__DOT__alu_result;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__result;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_dividend;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_divisor;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_quotient;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_remainder;
        VlWide<3>/*65:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_result_ss;
        VlWide<3>/*65:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_result_uu;
        VlWide<3>/*65:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_result_su;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk1__DOT__s;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk2__DOT__s;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk3__DOT__op1;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk3__DOT__op2;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk4__DOT__q;
        IData/*31:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk4__DOT__r;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk2__DOT__unnamedblk3__DOT__idx;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk4__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk7__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk7__DOT__unnamedblk9__DOT__c;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk7__DOT__unnamedblk9__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk7__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_stb__DOT__unnamedblk7__DOT__unnamedblk11__DOT__unnamedblk12__DOT__idx;
        IData/*31:0*/ core__DOT__lsu__DOT__u_ldb__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_ldb__DOT__unnamedblk3__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ core__DOT__lsu__DOT__u_ldb__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_ldb__DOT__unnamedblk9__DOT__num_flush;
        IData/*31:0*/ core__DOT__lsu__DOT__u_ldb__DOT__unnamedblk9__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_ldb__DOT__unnamedblk11__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_ldb__DOT__unnamedblk11__DOT__unnamedblk12__DOT__j;
    };
    struct {
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__lsu__DOT__u_dmem__DOT__unnamedblk9__DOT__i;
        IData/*31:0*/ core__DOT__register_file__DOT__i;
        IData/*31:0*/ core__DOT__ROB__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ core__DOT__ROB__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ core__DOT__ROB__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ core__DOT__ROB__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ core__DOT__ROB__DOT__unnamedblk8__DOT__unnamedblk9__DOT__j;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v64;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v65;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v66;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v67;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v68;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v69;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v70;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v71;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v72;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v73;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v74;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v75;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v76;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v77;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v78;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v79;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v80;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v81;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v82;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v83;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v84;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v85;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v86;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v87;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v88;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v89;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v90;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v91;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v92;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v93;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v94;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v95;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v96;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v97;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v98;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v99;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v100;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v101;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v102;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v103;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v104;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v105;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v106;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v107;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v108;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v109;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v110;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v111;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v112;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v113;
    };
    struct {
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v114;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v115;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v116;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v117;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v118;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v119;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v120;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v121;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v122;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v123;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v124;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v125;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v126;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v127;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v128;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v129;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v130;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v131;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v132;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v133;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v134;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v135;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v136;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v137;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v138;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v139;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v140;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__rename__DOT__tag_buffer__v141;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__int_cdb_lines__v3;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__int_cdb_lines__v4;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__int_cdb_lines__v5;
        IData/*31:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__result;
        IData/*31:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_divisor;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v16;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v17;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v18;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v19;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v20;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v21;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v22;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v23;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v24;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v25;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v26;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v27;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v28;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v29;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v30;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v31;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v32;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v33;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v34;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v35;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v36;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v37;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v37;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v38;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v39;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v40;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v41;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v41;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v42;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v43;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v43;
    };
    struct {
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v44;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v45;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v45;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v46;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v47;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v47;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v48;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v49;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v49;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v50;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v51;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v51;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v52;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v53;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v53;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v54;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v55;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v55;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v56;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v57;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v57;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v58;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v59;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v59;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v60;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v61;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v61;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v62;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v63;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v63;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v64;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v65;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v65;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v66;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v67;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v67;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v68;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v69;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v69;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v70;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v71;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v71;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v72;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v73;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v73;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v74;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v75;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v75;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v76;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v77;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v77;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v78;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v79;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v79;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v80;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v81;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v81;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v82;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v83;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v83;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v84;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v85;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v85;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v86;
    };
    struct {
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v87;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v87;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v88;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v89;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v89;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v90;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v91;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v91;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v92;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v93;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v93;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v94;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v95;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v95;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v96;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v97;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v97;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v98;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v99;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v99;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v100;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v101;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v101;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v102;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v103;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_ldb__DOT__entries__v103;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v104;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__u_ldb__DOT__entries__v105;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__ldb_mem_resp__v3;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__ldb_mem_resp__v4;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__ldb_mem_resp__v4;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__ldb_mem_resp__v6;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__lsu__DOT__ldb_mem_resp__v7;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__ldb_mem_resp__v7;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v0;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v1;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v2;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v3;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v4;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v5;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v6;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v7;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v8;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v9;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v10;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v11;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v12;
        IData/*31:0*/ __Vdlyvlsb__core__DOT__commit_packet__v13;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_dmem__DOT__rd_data_mem__v0;
        IData/*31:0*/ __Vdlyvval__core__DOT__lsu__DOT__u_dmem__DOT__rd_data_mem__v1;
        IData/*31:0*/ __VactIterCount;
        QData/*45:0*/ core__DOT____Vcellout__lsu__OUT_cdb;
        QData/*63:0*/ core__DOT__rename__DOT__ftb;
        VlWide<3>/*81:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__OUT_instr;
        VlWide<3>/*81:0*/ core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__OUT_instr;
        VlWide<3>/*81:0*/ core__DOT__issue__DOT____Vcellout__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__OUT_instr;
        VlWide<4>/*113:0*/ core__DOT__issue__DOT____Vcellout__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__OUT_instr;
        QData/*45:0*/ core__DOT__execute__DOT____Vcellout__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__OUT_cdb;
        VlWide<3>/*81:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__instr_r;
        QData/*63:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_partial;
        QData/*32:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_op1_s;
        QData/*32:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk5__DOT__partial_high;
        QData/*32:0*/ core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__unnamedblk5__DOT__sub_result;
        VlWide<3>/*73:0*/ core__DOT__lsu__DOT__stb_wb;
    };
    struct {
        QData/*42:0*/ core__DOT__lsu__DOT__ldb_addr_wb;
        QData/*45:0*/ __Vdlyvval__core__DOT__int_cdb_lines__v6;
        QData/*45:0*/ __Vdlyvval__core__DOT__int_cdb_lines__v7;
        QData/*45:0*/ __Vdlyvval__core__DOT__int_cdb_lines__v8;
        VlWide<3>/*81:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__instr_r;
        QData/*63:0*/ __Vdly__core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__div_partial;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__prefetch_instr;
        VlUnpacked<VlWide<3>/*71:0*/, 2> core__DOT__fetch_instr;
        VlUnpacked<VlWide<4>/*101:0*/, 2> core__DOT__decode_instr;
        VlUnpacked<CData/*5:0*/, 32> core__DOT__restore_specTag;
        VlUnpacked<CData/*0:0*/, 64> core__DOT__restore_free;
        VlUnpacked<IData/*18:0*/, 2> core__DOT__commit_packet;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 2>, 4> core__DOT__read_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 4> core__DOT__reg_ready;
        VlUnpacked<VlWide<4>/*104:0*/, 2> core__DOT__rename_instr;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__chkpt;
        VlUnpacked<CData/*6:0*/, 2> core__DOT__chkpt_sqN;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 2> core__DOT__store_specTag;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 64>, 2> core__DOT__store_free;
        VlUnpacked<QData/*45:0*/, 4> core__DOT__CDB;
        VlUnpacked<CData/*5:0*/, 4> core__DOT__CDB_tag;
        VlUnpacked<CData/*0:0*/, 4> core__DOT__CDB_valid;
        VlUnpacked<IData/*31:0*/, 4> core__DOT__CDB_result;
        VlUnpacked<CData/*6:0*/, 4> core__DOT__CDB_sqN;
        VlUnpacked<CData/*4:0*/, 2> core__DOT__rename_rob_rd;
        VlUnpacked<IData/*18:0*/, 2> core__DOT__rename_rob;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__alu_buffer_busy;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__mul_div_buffer_busy;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__lsu_buffer_busy;
        VlUnpacked<CData/*6:0*/, 2> core__DOT__commit_sqN;
        VlUnpacked<VlWide<4>/*102:0*/, 2> core__DOT__alu_dispatch_instr;
        VlUnpacked<IData/*29:0*/, 1> core__DOT__mul_div_dispatch_instr;
        VlUnpacked<QData/*62:0*/, 1> core__DOT__lsu_dispatch_instr;
        VlUnpacked<CData/*0:0*/, 4> core__DOT__issue_buffer_busy;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 2>, 4> core__DOT__RF_raddr;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 4> core__DOT__RF_read_data;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__mul_div_fu_busy;
        VlUnpacked<VlWide<3>/*81:0*/, 3> core__DOT__int_issue_instr;
        VlUnpacked<VlWide<4>/*113:0*/, 1> core__DOT__lsu_issue_instr;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__br_taken;
        VlUnpacked<CData/*1:0*/, 2> core__DOT__jump_type;
        VlUnpacked<CData/*6:0*/, 2> core__DOT__br_jalr_sqN;
        VlUnpacked<CData/*1:0*/, 2> core__DOT____Vcellinp__flush_controller__jump_type;
        VlUnpacked<CData/*6:0*/, 2> core__DOT____Vcellinp__flush_controller__sqN;
        VlUnpacked<CData/*0:0*/, 2> core__DOT____Vcellinp__flush_controller__br_taken;
        VlUnpacked<VlWide<3>/*76:0*/, 1> core__DOT__agu_out;
        VlUnpacked<QData/*45:0*/, 3> core__DOT__int_cdb_lines;
        VlUnpacked<QData/*45:0*/, 1> core__DOT__lsu_cdb_lines;
        VlUnpacked<IData/*31:0*/, 4> core__DOT__rs1_data;
        VlUnpacked<IData/*31:0*/, 4> core__DOT__rs2_data;
        VlUnpacked<CData/*5:0*/, 4> core__DOT__rs1_addr;
        VlUnpacked<CData/*5:0*/, 4> core__DOT__rs2_addr;
        VlUnpacked<IData/*31:0*/, 64> core__DOT__prefetch__DOT__IMEM__DOT__mem;
        VlUnpacked<VlWide<3>/*64:0*/, 2> core__DOT__fetch__DOT__aligner_out;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__fetch__DOT__pc_array;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__fetch__DOT__valid;
        VlUnpacked<CData/*6:0*/, 2> core__DOT__fetch__DOT__opcode;
        VlUnpacked<IData/*20:0*/, 2> core__DOT__fetch__DOT__imm;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__fetch__DOT__IA__DOT__pc_valid;
        VlUnpacked<VlWide<3>/*70:0*/, 16> core__DOT__fetch__DOT__FB__DOT__buffer;
        VlUnpacked<VlWide<4>/*101:0*/, 2> core__DOT__decode__DOT__decoder_out;
        VlUnpacked<CData/*6:0*/, 2> core__DOT__decode__DOT__Decoder__DOT__opcode;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__decode__DOT__Decoder__DOT__immediate;
        VlUnpacked<CData/*2:0*/, 64> core__DOT__rename__DOT__tag_buffer;
    };
    struct {
        VlUnpacked<SData/*11:0*/, 32> core__DOT__rename__DOT__rename_table;
        VlUnpacked<QData/*63:0*/, 3> core__DOT__rename__DOT__masked;
        VlUnpacked<QData/*63:0*/, 2> core__DOT__rename__DOT__onehot;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__rename__DOT__chosen;
        VlUnpacked<CData/*6:0*/, 64> core__DOT__rename__DOT__free_count;
        VlUnpacked<CData/*1:0*/, 2> core__DOT__rename__DOT__req_count;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 3> core__DOT__rename__DOT__local_rat;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__rename__DOT__free_CommTag;
        VlUnpacked<VlWide<4>/*102:0*/, 2> core__DOT__dispatch__DOT__alu_dispatch_out;
        VlUnpacked<IData/*29:0*/, 1> core__DOT__dispatch__DOT__mul_div_dispatch_out;
        VlUnpacked<QData/*62:0*/, 1> core__DOT__dispatch__DOT__lsu_dispatch_out;
        VlUnpacked<VlWide<4>/*104:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__packet;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__dispatched;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__alu_ready;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__dispatch__DOT__DU__DOT__mul_ready;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__dispatch__DOT__DU__DOT__lsu_ready;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__slot_pending;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__slot_is_alu;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__slot_is_mul;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__slot_is_lsu;
        VlUnpacked<CData/*1:0*/, 3> core__DOT__dispatch__DOT__DU__DOT__prefix_alu;
        VlUnpacked<CData/*1:0*/, 3> core__DOT__dispatch__DOT__DU__DOT__prefix_mul;
        VlUnpacked<CData/*1:0*/, 3> core__DOT__dispatch__DOT__DU__DOT__prefix_lsu;
        VlUnpacked<CData/*1:0*/, 3> core__DOT__dispatch__DOT__DU__DOT__prefix_ready_alu;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__prefix_ready_mul;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__prefix_ready_lsu;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__alu_slot;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__alu_valid;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__dispatch__DOT__DU__DOT__mul_slot;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__dispatch__DOT__DU__DOT__mul_valid;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__dispatch__DOT__DU__DOT__lsu_slot;
        VlUnpacked<CData/*0:0*/, 1> core__DOT__dispatch__DOT__DU__DOT__lsu_valid;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__dispatch__DOT__DU__DOT__can_dispatch;
        VlUnpacked<CData/*0:0*/, 16> core__DOT__dispatch__DOT__BC__DOT__valid;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 16> core__DOT__dispatch__DOT__BC__DOT__specTag;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 64>, 16> core__DOT__dispatch__DOT__BC__DOT__free;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__issue__DOT__pc;
        VlUnpacked<CData/*6:0*/, 2> core__DOT__issue__DOT__instr_sqN;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__issue__DOT__instr_valid;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__issue__DOT__alu_rs1_result;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__issue__DOT__alu_imm;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__read_tag;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__check_ready;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__RF_data;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__tag_ready;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__read_tag;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__check_ready;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__RF_data;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__tag_ready;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__read_tag;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__check_ready;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__RF_data;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__tag_ready;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__read_tag;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__issue__DOT____Vcellout__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__check_ready;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__RF_data;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__issue__DOT____Vcellinp__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__tag_ready;
        VlUnpacked<VlWide<4>/*104:0*/, 8> core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__queue;
        VlUnpacked<VlWide<4>/*104:0*/, 8> core__DOT__issue__DOT__gen_alu_buffer__BRA__0__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__next_queue;
        VlUnpacked<VlWide<4>/*104:0*/, 8> core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__queue;
        VlUnpacked<VlWide<4>/*104:0*/, 8> core__DOT__issue__DOT__gen_alu_buffer__BRA__1__KET____DOT__alu_issue_buffer_i__DOT__unnamedblk7__DOT__next_queue;
        VlUnpacked<IData/*31:0*/, 8> core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__queue;
        VlUnpacked<IData/*31:0*/, 8> core__DOT__issue__DOT__gen_mul_div_buffer__BRA__0__KET____DOT__mul_div_issue_buffer_i__DOT__unnamedblk7__DOT__v_queue;
        VlUnpacked<VlWide<3>/*64:0*/, 8> core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__queue;
    };
    struct {
        VlUnpacked<VlWide<3>/*64:0*/, 8> core__DOT__issue__DOT__gen_agu_buffer__BRA__0__KET____DOT__lsu_issue_buffer_i__DOT__unnamedblk7__DOT__v_queue;
        VlUnpacked<QData/*45:0*/, 3> core__DOT__execute__DOT__int_fu_out;
        VlUnpacked<VlWide<3>/*76:0*/, 1> core__DOT__execute__DOT__next_agu_out;
        VlUnpacked<QData/*63:0*/, 3> core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe;
        VlUnpacked<CData/*6:0*/, 3> core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_sqN;
        VlUnpacked<CData/*5:0*/, 3> core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_tag;
        VlUnpacked<CData/*3:0*/, 3> core__DOT__execute__DOT__gen_mul_div_fu__BRA__0__KET____DOT__MUL_DIV_i__DOT__mul_pipe_oper;
        VlUnpacked<VlWide<3>/*66:0*/, 2> core__DOT__lsu__DOT__stb_mem_req;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__mem_stall;
        VlUnpacked<QData/*42:0*/, 16> core__DOT__lsu__DOT__stb_fwd;
        VlUnpacked<QData/*42:0*/, 2> core__DOT__lsu__DOT__ldb_mem_req;
        VlUnpacked<QData/*39:0*/, 2> core__DOT__lsu__DOT__ldb_mem_resp;
        VlUnpacked<VlWide<3>/*75:0*/, 16> core__DOT__lsu__DOT__u_stb__DOT__entries;
        VlUnpacked<VlWide<3>/*82:0*/, 16> core__DOT__lsu__DOT__u_ldb__DOT__entries;
        VlUnpacked<CData/*3:0*/, 2> core__DOT__lsu__DOT__u_ldb__DOT__req_idx;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_stall;
        VlUnpacked<VlWide<3>/*66:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__wr_req_held;
        VlUnpacked<QData/*42:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_req_held;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__wr_pending;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_pending;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__wr_ack_sync;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_ack_sync;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__wr_valid_sync;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_valid_sync;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 128>, 2> core__DOT__lsu__DOT__u_dmem__DOT__bank;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__wr_ack_mem;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_ack_mem;
        VlUnpacked<IData/*31:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_data_mem;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_tag_mem;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_resp_valid_mem;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__wr_valid_sync_r;
        VlUnpacked<CData/*0:0*/, 2> core__DOT__lsu__DOT__u_dmem__DOT__rd_valid_sync_r;
        VlUnpacked<IData/*31:0*/, 64> core__DOT__register_file__DOT__registers;
        VlUnpacked<IData/*18:0*/, 64> core__DOT__ROB__DOT__rob;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__ROB__DOT__alloc_index;
        VlUnpacked<CData/*5:0*/, 2> core__DOT__ROB__DOT__commit_index;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_alu__0;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_ready_alu__0;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_mul__0;
        VlUnpacked<CData/*0:0*/, 2> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_ready_mul__0;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_lsu__0;
        VlUnpacked<CData/*0:0*/, 2> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_ready_lsu__0;
        VlUnpacked<QData/*63:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__rename__DOT__masked__0;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_alu__1;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_ready_alu__1;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_mul__1;
        VlUnpacked<CData/*0:0*/, 2> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_ready_mul__1;
        VlUnpacked<CData/*1:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_lsu__1;
        VlUnpacked<CData/*0:0*/, 2> __Vtrigprevexpr___TOP__core__DOT__dispatch__DOT__DU__DOT__prefix_ready_lsu__1;
        VlUnpacked<QData/*63:0*/, 3> __Vtrigprevexpr___TOP__core__DOT__rename__DOT__masked__1;
        VlUnpacked<CData/*0:0*/, 11> __Vm_traceActivity;
    };
    VlTriggerVec<9> __VstlTriggered;
    VlTriggerVec<11> __VactTriggered;
    VlTriggerVec<11> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vcore__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vcore___024root(Vcore__Syms* symsp, const char* v__name);
    ~Vcore___024root();
    VL_UNCOPYABLE(Vcore___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
