onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -height 25 /tb_core/clk
add wave -noupdate -height 25 /tb_core/clk_m
add wave -noupdate -height 25 /tb_core/rst
add wave -noupdate -height 25 /tb_core/rst_m
add wave -noupdate -height 25 /tb_core/tests_run
add wave -noupdate -height 25 /tb_core/tests_fail
add wave -noupdate -height 25 /tb_core/#ublk#176531189#32/#ublk#176531189#76/cycle
add wave -noupdate -height 25 /tb_core/dut/clk
add wave -noupdate -height 25 /tb_core/dut/clk_m
add wave -noupdate -height 25 /tb_core/dut/rst
add wave -noupdate -height 25 /tb_core/dut/rst_m
add wave -noupdate -height 25 /tb_core/dut/fb_busy
add wave -noupdate -height 25 /tb_core/dut/jump1
add wave -noupdate -height 25 /tb_core/dut/jump2
add wave -noupdate -height 25 /tb_core/dut/jta1
add wave -noupdate -height 25 /tb_core/dut/jta2
add wave -noupdate -height 25 /tb_core/dut/rename_busy
add wave -noupdate -height 25 /tb_core/dut/flush
add wave -noupdate -height 25 /tb_core/dut/ROB_busy
add wave -noupdate -height 25 /tb_core/dut/chkpt_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch_unit_busy
add wave -noupdate -height 25 /tb_core/dut/lsu_busy
add wave -noupdate -height 25 /tb_core/dut/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/prefetch/clk
add wave -noupdate -height 25 /tb_core/dut/prefetch/rst
add wave -noupdate -height 25 /tb_core/dut/prefetch/jta1
add wave -noupdate -height 25 /tb_core/dut/prefetch/jta2
add wave -noupdate -height 25 /tb_core/dut/prefetch/jump1
add wave -noupdate -height 25 /tb_core/dut/prefetch/jump2
add wave -noupdate -height 25 /tb_core/dut/prefetch/fetch_base
add wave -noupdate -height 25 /tb_core/dut/prefetch/IN_busy
add wave -noupdate -height 25 /tb_core/dut/prefetch/next_pc
add wave -noupdate -height 25 /tb_core/dut/prefetch/current_pc
add wave -noupdate -height 25 /tb_core/dut/prefetch/actual_pc
add wave -noupdate -height 25 /tb_core/dut/prefetch/instr_consumed
add wave -noupdate -height 25 /tb_core/dut/prefetch/PC/clk
add wave -noupdate -height 25 /tb_core/dut/prefetch/PC/rst
add wave -noupdate -height 25 /tb_core/dut/prefetch/PC/IN_pc
add wave -noupdate -height 25 /tb_core/dut/prefetch/PC/wr_en
add wave -noupdate -height 25 /tb_core/dut/prefetch/PC/OUT_pc
add wave -noupdate -height 25 /tb_core/dut/prefetch/PC/pc_reg
add wave -noupdate -height 25 /tb_core/dut/prefetch/IMEM/clk
add wave -noupdate -height 25 /tb_core/dut/prefetch/IMEM/rst
add wave -noupdate -height 25 /tb_core/dut/prefetch/IMEM/IN_busy
add wave -noupdate -height 25 /tb_core/dut/prefetch/IMEM/addr
add wave -noupdate -height 25 /tb_core/dut/prefetch/IMEM/block_idx
add wave -noupdate -height 25 /tb_core/dut/prefetch/IMEM/base_word
add wave -noupdate -height 25 /tb_core/dut/prefetch/aligner/in_pc
add wave -noupdate -height 25 /tb_core/dut/prefetch/aligner/consumed
add wave -noupdate -height 25 /tb_core/dut/prefetch/aligner/is_aligned
add wave -noupdate -height 25 /tb_core/dut/prefetch/aligner/aligned_base_pc
add wave -noupdate -height 25 /tb_core/dut/fetch/clk
add wave -noupdate -height 25 /tb_core/dut/fetch/rst
add wave -noupdate -height 25 /tb_core/dut/fetch/IN_busy
add wave -noupdate -height 25 /tb_core/dut/fetch/flush
add wave -noupdate -height 25 /tb_core/dut/fetch/OUT_busy
add wave -noupdate -height 25 /tb_core/dut/fetch/jump1
add wave -noupdate -height 25 /tb_core/dut/fetch/jta1
add wave -noupdate -height 25 /tb_core/dut/fetch/JTA1/jump1
add wave -noupdate -height 25 /tb_core/dut/fetch/JTA1/jta1
add wave -noupdate -height 25 /tb_core/dut/fetch/JTA1/jump_valid
add wave -noupdate -height 25 /tb_core/dut/fetch/JTA1/jump_index
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/clk
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/rst
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/IN_busy
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/flush
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/OUT_busy
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/head
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/tail
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/count
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/out_count
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/can_write
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/can_read
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/#anonblk#56059170#46#4#/#ublk#56059170#46/sum
add wave -noupdate -height 25 /tb_core/dut/fetch/FB/#anonblk#56059170#57#4#/#ublk#56059170#57/sum
add wave -noupdate -height 25 /tb_core/dut/decode/clk
add wave -noupdate -height 25 /tb_core/dut/decode/rst
add wave -noupdate -height 25 /tb_core/dut/decode/IN_busy
add wave -noupdate -height 25 /tb_core/dut/decode/flush
add wave -noupdate -height 25 /tb_core/dut/decode/next_sqN
add wave -noupdate -height 25 /tb_core/dut/decode/valid_count
add wave -noupdate -height 25 /tb_core/dut/decode/Decoder/IG/funct3
add wave -noupdate -height 25 /tb_core/dut/decode/Decoder/IG/opcode
add wave -noupdate -height 25 /tb_core/dut/decode/Decoder/IG/imm12
add wave -noupdate -height 25 /tb_core/dut/decode/Decoder/IG/imm13
add wave -noupdate -height 25 /tb_core/dut/decode/Decoder/IG/imm21
add wave -noupdate -height 25 /tb_core/dut/decode/Decoder/IG/iw
add wave -noupdate -height 25 /tb_core/dut/rename/clk
add wave -noupdate -height 25 /tb_core/dut/rename/rst
add wave -noupdate -height 25 /tb_core/dut/rename/ROB_busy
add wave -noupdate -height 25 /tb_core/dut/rename/dispatch_busy
add wave -noupdate -height 25 /tb_core/dut/rename/flush
add wave -noupdate -height 25 /tb_core/dut/rename/chkpt_busy
add wave -noupdate -height 25 /tb_core/dut/rename/OUT_busy
add wave -noupdate -height 25 /tb_core/dut/rename/ftb
add wave -noupdate -height 25 /tb_core/dut/rename/req_valid
add wave -noupdate -height 25 /tb_core/dut/rename/chkpt_need
add wave -noupdate -height 25 /tb_core/dut/rename/stall
add wave -noupdate -height 25 /tb_core/dut/dispatch/clk
add wave -noupdate -height 25 /tb_core/dut/dispatch/rst
add wave -noupdate -height 25 /tb_core/dut/dispatch/LSU_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch/flush
add wave -noupdate -height 25 /tb_core/dut/dispatch/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/dispatch/d_unit_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch/check_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch/DU/clk
add wave -noupdate -height 25 /tb_core/dut/dispatch/DU/rst
add wave -noupdate -height 25 /tb_core/dut/dispatch/DU/flush
add wave -noupdate -height 25 /tb_core/dut/dispatch/DU/LSU_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch/DU/OUT_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch/DU/packet_done
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/clk
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/rst
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/flush
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/disp_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/check_busy
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/used_count
add wave -noupdate -height 25 /tb_core/dut/dispatch/BC/slot_collision
add wave -noupdate -height 25 /tb_core/dut/issue/clk
add wave -noupdate -height 25 /tb_core/dut/issue/rst
add wave -noupdate -height 25 /tb_core/dut/issue/flush
add wave -noupdate -height 25 /tb_core/dut/issue/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/issue/jta2
add wave -noupdate -height 25 /tb_core/dut/issue/jump2
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/clk}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/rst}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/flush}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/flush_sqN}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/OUT_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/OUT_busy}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/ready_mask}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/issue_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/issue_found}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/next_tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/next_issue_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/registered_out_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/pe/req}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/pe/grant_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_agu_buffer[0]/lsu_issue_buffer_i/pe/grant_valid}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/clk}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/rst}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/flush}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/flush_sqN}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/IN_busy}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/OUT_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/OUT_busy}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/ready_mask}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/issue_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/issue_found}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/rs1_data}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/rs2_data}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/next_tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/next_issue_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/registered_out_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/pe/req}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/pe/grant_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_mul_div_buffer[0]/mul_div_issue_buffer_i/pe/grant_valid}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/clk}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/rst}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/flush}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/flush_sqN}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/OUT_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/OUT_br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/OUT_jump_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/OUT_pc}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/rs1_result}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/imm}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/OUT_busy}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/ready_mask}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/issue_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/issue_found}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/op1}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/op2}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/sel1}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/sel2}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/sel_ready2}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/next_tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/next_issue_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/next_pc}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/next_jump_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/next_rs1_result}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/next_imm}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/next_br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/registered_out_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/registered_pc}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/registered_rs1_result}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/registered_imm}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/registered_br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/registered_jump_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/pe/req}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/pe/grant_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/pe/grant_valid}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/bc/rs1_data}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/bc/rs2_data}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/bc/br_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[1]/alu_issue_buffer_i/bc/br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/clk}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/rst}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/flush}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/flush_sqN}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/OUT_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/OUT_br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/OUT_jump_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/OUT_pc}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/rs1_result}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/imm}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/OUT_busy}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/ready_mask}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/issue_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/issue_found}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/op1}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/op2}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/sel1}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/sel2}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/sel_ready2}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/next_tail}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/next_issue_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/next_pc}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/next_jump_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/next_rs1_result}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/next_imm}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/next_br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/registered_out_instr}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/registered_pc}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/registered_rs1_result}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/registered_imm}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/registered_br_taken}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/registered_jump_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/pe/req}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/pe/grant_idx}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/pe/grant_valid}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/bc/rs1_data}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/bc/rs2_data}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/bc/br_type}
add wave -noupdate -height 25 {/tb_core/dut/issue/gen_alu_buffer[0]/alu_issue_buffer_i/bc/br_taken}
add wave -noupdate -height 25 /tb_core/dut/issue/ta_gen2/jta2
add wave -noupdate -height 25 /tb_core/dut/issue/ta_gen2/jump2
add wave -noupdate -height 25 /tb_core/dut/issue/ta_gen2/oldest_idx
add wave -noupdate -height 25 /tb_core/dut/issue/ta_gen2/oldest_sqN
add wave -noupdate -height 25 /tb_core/dut/flush_controller/clk
add wave -noupdate -height 25 /tb_core/dut/flush_controller/rst
add wave -noupdate -height 25 /tb_core/dut/flush_controller/flush
add wave -noupdate -height 25 /tb_core/dut/flush_controller/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/flush_controller/#ublk#41387346#19/best_sqN
add wave -noupdate -height 25 /tb_core/dut/flush_controller/#ublk#41387346#19/any_valid
add wave -noupdate -height 25 /tb_core/dut/flush_controller/#ublk#41387346#19/diff
add wave -noupdate -height 25 /tb_core/dut/execute/clk
add wave -noupdate -height 25 /tb_core/dut/execute/rst
add wave -noupdate -height 25 /tb_core/dut/execute/flush
add wave -noupdate -height 25 /tb_core/dut/execute/flush_sqN
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_agu_fu[0]/AGU_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_agu_fu[0]/AGU_i/OUT}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_agu_fu[0]/AGU_i/is_load}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_agu_fu[0]/AGU_i/is_store}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_agu_fu[0]/AGU_i/data_size}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_agu_fu[0]/AGU_i/is_unsigned}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_agu_fu[0]/AGU_i/target_addr}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/clk}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/rst}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/flush}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/flush_sqN}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/OUT_busy}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/OUT_cdb}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/mul_stall}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/mul_cdb_valid}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/mul_cdb_sqN}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/mul_cdb_tag}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/mul_cdb_result}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_state}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_instr_r}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_partial}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_divisor}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_count}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_quot_sign}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_rem_sign}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_by_zero}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_cdb_valid}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_cdb_sqN}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_cdb_tag}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/div_cdb_result}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/mul_stage1_result}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/mul_stage2_result}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#94/full}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#94/upper}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#94/partial}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#200/op1}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#200/op2}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#280/op1}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#280/op2}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#280/s1}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#280/s2}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#317/q}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#317/r}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#331/partial_high}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#331/sub_result}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#364/mul_result_ready}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_mul_div_fu[0]/MUL_DIV_i/#ublk#44185782#364/div_result_ready}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_alu_fu[1]/ALU_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_alu_fu[1]/ALU_i/OUT}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_alu_fu[1]/ALU_i/alu_result}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_alu_fu[0]/ALU_i/IN_instr}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_alu_fu[0]/ALU_i/OUT}
add wave -noupdate -height 25 {/tb_core/dut/execute/gen_alu_fu[0]/ALU_i/alu_result}
add wave -noupdate -height 25 /tb_core/dut/lsu/clk
add wave -noupdate -height 25 /tb_core/dut/lsu/clk_m
add wave -noupdate -height 25 /tb_core/dut/lsu/rst
add wave -noupdate -height 25 /tb_core/dut/lsu/rst_m
add wave -noupdate -height 25 /tb_core/dut/lsu/flush
add wave -noupdate -height 25 /tb_core/dut/lsu/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/lsu/OUT_busy
add wave -noupdate -height 25 /tb_core/dut/lsu/store_disp_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/load_disp_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/has_store_disp
add wave -noupdate -height 25 /tb_core/dut/lsu/has_load_disp
add wave -noupdate -height 25 /tb_core/dut/lsu/store_agu_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/load_agu_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/has_store_agu
add wave -noupdate -height 25 /tb_core/dut/lsu/has_load_agu
add wave -noupdate -height 25 /tb_core/dut/lsu/str_busy
add wave -noupdate -height 25 /tb_core/dut/lsu/stb_alloc
add wave -noupdate -height 25 /tb_core/dut/lsu/stb_wb
add wave -noupdate -height 25 /tb_core/dut/lsu/ld_busy
add wave -noupdate -height 25 /tb_core/dut/lsu/ldb_alloc
add wave -noupdate -height 25 /tb_core/dut/lsu/ldb_addr_wb
add wave -noupdate -height 25 /tb_core/dut/lsu/ldb_cdb_out
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/clk
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/rst
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/alloc
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/wb
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/flush
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/str_busy
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/alloc_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/wb_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/u_stb/used_count
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/clk
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/rst
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/alloc
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/addr_wb
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/flush
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/cdb_out
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/ld_busy
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/alloc_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/ta_wb_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/broadcast_idx
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/broadcast_valid
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/used_count
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#130/is_older
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#130/addr_covers
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#130/ld_lanes
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#130/st_lanes
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#130/found_match
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#130/youngest_sqN
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#130/youngest_j
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#226/#anonblk#99130210#229#4#/#ublk#99130210#229/can_issue
add wave -noupdate -height 25 /tb_core/dut/lsu/u_ldb/#ublk#99130210#226/#anonblk#99130210#242#4#/#ublk#99130210#242/can_issue
add wave -noupdate -height 25 /tb_core/dut/lsu/u_dmem/clk_cpu
add wave -noupdate -height 25 /tb_core/dut/lsu/u_dmem/rst_cpu
add wave -noupdate -height 25 /tb_core/dut/lsu/u_dmem/clk_mem
add wave -noupdate -height 25 /tb_core/dut/lsu/u_dmem/rst_mem
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_wr_ack/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_wr_ack/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_wr_ack/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_wr_ack/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_wr_ack/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_wr_ack/ff2}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_rd_ack/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_rd_ack/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_rd_ack/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_rd_ack/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_rd_ack/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[1]/u_rd_ack/ff2}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_wr_ack/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_wr_ack/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_wr_ack/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_wr_ack/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_wr_ack/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_wr_ack/ff2}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_rd_ack/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_rd_ack/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_rd_ack/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_rd_ack/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_rd_ack/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_ack_sync[0]/u_rd_ack/ff2}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_wr_sync/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_wr_sync/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_wr_sync/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_wr_sync/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_wr_sync/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_wr_sync/ff2}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_rd_sync/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_rd_sync/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_rd_sync/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_rd_sync/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_rd_sync/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[1]/u_rd_sync/ff2}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_wr_sync/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_wr_sync/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_wr_sync/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_wr_sync/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_wr_sync/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_wr_sync/ff2}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_rd_sync/clk_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_rd_sync/rst_dst}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_rd_sync/d}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_rd_sync/q}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_rd_sync/ff1}
add wave -noupdate -height 25 {/tb_core/dut/lsu/u_dmem/g_req_sync[0]/u_rd_sync/ff2}
add wave -noupdate -height 25 /tb_core/dut/lsu/u_dmem/#anonblk#106089705#180#4#/#ublk#106089705#183/be
add wave -noupdate -height 25 /tb_core/dut/lsu/u_dmem/#anonblk#106089705#180#4#/#ublk#106089705#183/bsel
add wave -noupdate -height 25 /tb_core/dut/lsu/u_dmem/#anonblk#106089705#180#4#/#ublk#106089705#183/boff
add wave -noupdate -height 25 /tb_core/dut/register_file/clk
add wave -noupdate -height 25 /tb_core/dut/register_file/rst
add wave -noupdate -height 25 /tb_core/dut/register_file/i
add wave -noupdate -height 25 /tb_core/dut/ROB/clk
add wave -noupdate -height 25 /tb_core/dut/ROB/rst
add wave -noupdate -height 25 /tb_core/dut/ROB/flush
add wave -noupdate -height 25 /tb_core/dut/ROB/flush_sqN
add wave -noupdate -height 25 /tb_core/dut/ROB/OUT_busy
add wave -noupdate -height 25 /tb_core/dut/ROB/count
add wave -noupdate -height 25 /tb_core/dut/ROB/head
add wave -noupdate -height 25 /tb_core/dut/ROB/tail
add wave -noupdate -height 25 /tb_core/dut/ROB/full
add wave -noupdate -height 25 /tb_core/dut/ROB/empty
add wave -noupdate -height 25 /tb_core/dut/ROB/num_write
add wave -noupdate -height 25 /tb_core/dut/ROB/num_commit
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {203 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 218
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {591 ns}
